sudo: required
dist: trusty
language: node_js
node_js:
    - '6'
    - '4'
before_install: ./test/setup.sh
script: npm test
after_script: npm run test-coverage && cat ./coverage/lcov.info | coveralls
